name: ci-desafio
on:
  pull_request:
    branches:
      - develop
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v2
        with:
          node-version: 10.x  
      - run: npm install  
      - run: npm run build --if-present
      - run: npm run test
      #- name: SonarCloud Scan
      #  uses: SonarSource/sonarcloud-github-action@master
        env:
          CI: false
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
       #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}